apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  labels:
    app: testjob
spec:
  template:
    metadata:
      name: testjob
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      restartPolicy: Never
      volumes:
        - name: var-www
          persistentVolumeClaim:
            claimName: wordpress-raynix
        - name: gcp-sa
          secret:
            secretName: backup-gcp-sa
      containers:
        - name: backup-tool
          image: ghcr.io/raynix/backup:v0.20
          command:
            - sleep
            - "3600"

          envFrom:
            - secretRef:
                name: wordpress-secret
          volumeMounts:
            - name: var-www
              mountPath: /wordpress
            - name: gcp-sa
              mountPath: /gcp
