apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bay-leaves
  namespace: argocd
spec:
  destination:
    namespace: bay-leaves
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /
    repoURL: https://github.com/raynix/bay-leaves.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
