apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  destination:
    namespace: istio-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/charts/istio-operator
    repoURL: https://github.com/istio/istio
    targetRevision: release-1.22
    helm:
      values: |
        # https://github.com/istio/istio/blob/release-1.22/manifests/charts/istio-operator/values.yaml
        deploymentHistory: 3
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
