apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon-awes-one
bases:
  - ../base

commonAnnotations:
  domain: awes.one
  cert: awes-one-cert

resources:
  - ns.yaml
  - pv.yaml
  - ss.yaml

images:
  - name: tootsuite/mastodon
    newTag: v4.0.2
  - name: ghcr.io/raynix/backup
    newTag: v0.29
