apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lucky-birdie
  namespace: argocd
spec:
  destination:
    namespace: lucky-birdie
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .kustomize
    repoURL: https://github.com/raynix/shuttle-buddy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
