apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  destination:
    namespace: bootstrap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: obsidian-cluster/bootstrap
    repoURL: https://github.com/raynix/argo-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
