---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saus-dev
  namespace: argocd
spec:
  destination:
    namespace: saus-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .kustomize/dev.sausl.ink
    repoURL: https://github.com/raynix/saus.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saus-prod
  namespace: argocd
spec:
  destination:
    namespace: saus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .kustomize/sausl.ink
    repoURL: https://github.com/raynix/saus.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
