---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yopass
  namespace: argocd
spec:
  destination:
    namespace: yopass
    server: https://kubernetes.default.svc
  project: default
  source:
    path: yopass
    repoURL: https://github.com/raynix/argo-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
