apiVersion: batch/v1
kind: CronJob
metadata:
  name: mastodon-media-remove-orphans
  labels:
    app: mastodon-media-remove-orphans
spec:
  schedule: 0 0 * * 0
  jobTemplate:
    spec:
      template:
        metadata:
          name: mastodon-media-remove-orphans
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
          restartPolicy: OnFailure
          volumes:
            - name: assets
              persistentVolumeClaim:
                claimName: mastodon-assets
            - name: system
              persistentVolumeClaim:
                claimName: mastodon-system
            - name: flags
              emptyDir: {}
          containers:
            - name: curl
              image: curlimages/curl:7.78.0
              command:
                - /bin/sh
                - -c
                - |
                  rm -rf /tmp/flags/*
                  until curl -fsI http://localhost:15021/healthz/ready; do
                    echo 'Waiting for Sidecar...'
                    sleep 1
                  done
                  touch /tmp/flags/istio-proxy-ready
                  until [ -f /tmp/flags/done ]; do
                    echo 'Waiting for the job to finish...'
                    sleep 1
                  done
                  curl -fsI -X POST http://localhost:15020/quitquitquit

              volumeMounts:
                - name: flags
                  mountPath: /tmp/flags

            - name: mastodon-media-remove-orphans
              image: "tootsuite/mastodon:v3.3.0"
              command:
                - /bin/bash
                - -c
                - |
                  until [[ -f /tmp/flags/istio-proxy-ready ]]; do
                    echo 'Waiting for Sidecar...'
                    sleep 1
                  done
                  bin/tootctl media remove-orphans
                  touch /tmp/flags/done
              envFrom:
                - secretRef:
                    name: mastodon
              volumeMounts:
                - name: assets
                  mountPath: /opt/mastodon/public/assets
                - name: system
                  mountPath: /opt/mastodon/public/system
                - name: flags
                  mountPath: /tmp/flags
