---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # set to trigger before a sync starts
    argocd.argoproj.io/hook: PreSync
    # delete the existing one before sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: mastodon-db-migrate
  labels:
    app: mastodon-db-migrate
spec:
  template:
    metadata:
      name: mastodon-db-migrate
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      restartPolicy: Never
      containers:
        - name: mastodon-db-migrate
          image: "ghcr.io/mastodon/mastodon:v3.3.0"
          command:
            - /bin/bash
            - -c
            - |
              bundle exec rails db:migrate
          envFrom:
            - secretRef:
                name: mastodon
