---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mastodon-web
      domain: $(DOMAIN)
  template:
    metadata:
      labels:
        app: mastodon-web
        domain: $(DOMAIN)
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mastodon-web
                    - key: domain
                      operator: In
                      values:
                        - $(DOMAIN)
                topologyKey: "kubernetes.io/hostname"
      securityContext:
        fsGroup: 991
        runAsGroup: 991
        runAsUser: 991
      containers:
        - name: web
          image: tootsuite/mastodon:v3.3.0
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          ports:
            - name: web
              containerPort: 3000
          envFrom:
            - secretRef:
                name: mastodon
          resources:
            requests:
              memory: 350Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /health
              port: web
          readinessProbe:
            httpGet:
              path: /health
              port: web
          volumeMounts:
            - name: public-system
              mountPath: /opt/mastodon/public/system
            - name: public-assets
              mountPath: /opt/mastodon/public/assets
      volumes:
        - name: public-system
          persistentVolumeClaim:
            claimName: mastodon-system
        - name: public-assets
          persistentVolumeClaim:
            claimName: mastodon-assets
---
apiVersion: v1
kind: Service
metadata:
  name: mastodon-web
spec:
  ports:
    - name: http-web
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: mastodon-web
