apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - conf.yaml

resources:
  - deploy.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - redis.yaml
  - ns.yaml
  - cronjob-backup.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
  - name: php-config
    files:
      - php.ini
  - name: wordpress-nginx-config
    files:
      - wordpress-nginx.conf

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: wordpress
    fieldref:
      fieldpath: metadata.labels.domain
