apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-dote
  namespace: istio-system
spec:
  secretName: wordpress-dote-cert
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - dote.blog
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - dote.blog
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
