apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - ns.yaml
  - deploy.yaml
  - pv.yaml
  - pvc.yaml
  - svc.yaml
  - gateway.yaml
  - virtual-service.yaml

images:
  - name: grafana/grafana
    newTag: 8.0.2
