apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gsm
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              namespace: external-secrets
              key: secret-access-credentials
        projectID: idyllic-depth-239301
