apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
spec:
  template:
    spec:
      containers:
        - name: reflector
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 500m