apiVersion: v1
kind: Namespace
metadata:
  name: cnrm-system

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: idyllic-depth-239301
  name: config-connector-resources
