apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress-ronia
bases:
  - ../base

nameSuffix: -ronia
commonLabels:
  domain: ronia.raynix.info

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/raynix/backup
    newTag: v0.28
