apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- upstream.yaml

configMapGenerator:
- files:
  - plugin.yaml
  name: cmp-tanka
patches:
- path: patch.yaml
