apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - upstream.yaml

patchesStrategicMerge:
  - patch.yaml

configMapGenerator:
  - name: cmp-tanka
    files:
      - plugin.yaml
