---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        # for tanka plugin
        - name: sideloader
          mountPath: /sideloader
      initContainers:
      # for tanka plugin
      - name: sideloader
        image: ghcr.io/raynix/sideloader:latest
        args:
        # args are processed in pairs
          - tk
          - https://github.com/grafana/tanka/releases/download/v0.25.0/tk-linux-amd64
          - jb
          - https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.5.1/jb-linux-amd64
        volumeMounts:
          - name: sideloader
            mountPath: /sideloader
      volumes:
      # for tanka plugin
      - name: sideloader
        emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: tanka
      init:
        command: ["/sideloader/jb"]
        args: ["install"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["/sideloader/tk show environments/${ARGOCD_ENV_TK_ENV} --dangerous-allow-redirect"]

  resource.customizations.health.bitnami.com_SealedSecret: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Controller doesn't report resource status"
    return hs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
