apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: grafana
spec:
  gateways:
  - grafana-gateway
  hosts:
  - grafana.awes.one
  http:
  - route:
    - destination:
        host: loki-stack-charts-grafana
