apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# master switches for all apps and components
resources:
  - argo-istio.yaml
  - csi-driver-nfs.yaml
  - sealed-secrets.yaml
  - reflector.yaml
  - prometheus.yaml
  - cert-manager.yaml
  - certificates.yaml
  - kube-state-metrics.yaml
  - httpbin.yaml
  - saus.yaml
  - kubecraft.yaml
  - wordpress-sophie.yaml
  - wordpress-dote.yaml
  - wordpress-ronia.yaml
  - wordpress-raynix.yaml
  - mastodon-awes-one.yaml