apiVersion: v1
data:
  configManagementPlugins: |
    - name: tanka
      init:
        command: ["/sideloader/jb"]
        args: ["install"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["/sideloader/tk show environments/${ARGOCD_ENV_TK_ENV} --dangerous-allow-redirect"]

  resource.customizations.health.bitnami.com_SealedSecret: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Controller doesn't report resource status"
    return hs

kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
