apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - argo.awes.one
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: awes-one-cert
  - hosts:
    - argo.awes.one
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true