apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  gateways:
  - argocd-gateway
  hosts:
  - argo.awes.one
  http:
  - route:
    - destination:
        host: argocd-server
