apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  gateways:
    - istio-system/awes-gateway
  hosts:
    - argo.awes.one
  http:
    - route:
      - destination:
          host: argocd-server
          port:
            number: 80
