apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  gateways:
    - argocd-gateway
  hosts:
    - argo.awes.one
  tls:
    - match:
        - port: 443
          sniHosts:
            - argo.awes.one
      route:
        - destination:
            host: argocd-server
            port:
              number: 443

