---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  refreshInterval: 720h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-api-token
